### ISSUE TITLE
No module name csv_parser

### ISSUE THREAD

**Issue by vedantshetty** [samarsault/CSV-Mapper#11]
When I try to run the example  code on python 3 i get 
`from csv_parser import CSVParser,CSVWriter`
`ModuleNoteFoundError: No module name csv_parser`

**Comment by pkallu** [comment]
I am getting the same issue. Let me know how to fix it

**Comment by cocopapagal** [comment]
Same issue for me. Python version 3.6
Please let me know how to fix it.

**Comment by thelehhman** [comment]
The new version had not been uploaded to pypi.
Fixed in 9ff444fc4e0d01a679a62d92ffe9ec62b9b286b3

It should work fine once you re-install it.🙂
Sorry for the delay
